import { ServiceData } from "./types";

export const AI_AUTOMATION_SERVICES: Record<string, ServiceData> = {
  "hub": {
    slug: "ai-automation",
    route: "/ai-automation",
    title: "AI & Automation Services | Autonomous Agents & Workflows | SARS Global",
    eyebrow: "Enterprise AI & Intelligent Automation",
    metaDescription: "Streamline operations, eliminate manual bottlenecks, and scale with SARS Global's AI automation services: autonomous AI agents, smart chatbots, CRM automation, and workflow integration.",
    heroHeadline: "Enterprise AI & Autonomous Automation That Powers Scale",
    heroSubheadline: "We build custom AI agents, self-orchestrating workflows, intelligent chatbots, and deep CRM automations that eliminate repetitive business labor and multiply team productivity.",
    badges: ["Autonomous AI Agents", "Custom LLM & GPT Workflows", "Intelligent Chatbots", "End-to-End Workflow Automation", "CRM & ERP Integration", "Automated Lead Routing"],
    challenge: {
      title: "The Manual Operations Bottleneck",
      description: "Growing businesses lose hundreds of employee hours each month to repetitive operational tasks: manual data entry between siloed tools, delayed customer inquiry follow-ups, and fragmented operational handoffs. Off-the-shelf software tools solve individual problems but fail to connect the dots.",
      points: [
        "Knowledge workers spending up to 40% of their day copying and pasting data across disconnected systems",
        "Slow customer response times leading to lost sales opportunities and lower CSAT scores",
        "Human errors in document processing, invoice reconciliation, and CRM data management",
        "Difficulty scaling operational volume without proportionally hiring more headcount",
      ],
    },
    solutions: [
      {
        title: "Autonomous AI Agents",
        desc: "Goal-directed AI agents capable of reasoning, executing multi-step business actions, pulling data from APIs, and collaborating with your team.",
        deliverables: ["Custom tool-use & API integration", "Multi-modal document analysis agents", "Autonomous research & lead enrichment", "Human-in-the-loop oversight guardrails"],
      },
      {
        title: "Intelligent AI Chatbots & Assistants",
        desc: "Domain-trained conversational AI that understands complex product catalogs, resolves support tickets, and qualifies sales prospects 24/7.",
        deliverables: ["RAG (Retrieval-Augmented Generation) on internal docs", "Omnichannel deployment (Web, WhatsApp, Slack)", "CRM lead capture & instant booking", "Live agent handoff escalation rules"],
      },
      {
        title: "Workflow & Operations Automation",
        desc: "Connecting your business applications into synchronized, autonomous event-driven pipelines that eliminate manual handoffs.",
        deliverables: ["Cross-platform data synchronization", "Automated customer onboarding workflows", "Invoice, contract & receipt parsing", "Exception alerting & failure recovery"],
      },
      {
        title: "CRM & Marketing Automation",
        desc: "Intelligent lead scoring, automated multi-channel follow-ups, dynamic pipeline stage updates, and personalized email nurturing.",
        deliverables: ["HubSpot, Salesforce, Zoho & Pipedrive automation", "Behavioral lead scoring models", "Dynamic personalization sequences", "Closed-loop revenue attribution"],
      },
    ],
    subServices: [
      {
        title: "AI Agent Development",
        route: "/ai-automation/ai-agent-development",
        desc: "Deploy autonomous AI agents that reason through multi-step tasks, call APIs, and execute complex business actions.",
        deliverables: ["Autonomous Agents", "Tool-Calling APIs", "Multi-Step Reasoning", "Enterprise Guardrails"],
      },
      {
        title: "AI Chatbot Development",
        route: "/ai-automation/ai-chatbot-development",
        desc: "Custom RAG-powered chatbots trained on your company data that handle customer support and sales qualification 24/7.",
        deliverables: ["Domain-Trained RAG", "Omnichannel Bots", "CRM Auto-Sync", "Support Ticket Deflection"],
      },
      {
        title: "Workflow Automation",
        route: "/ai-automation/workflow-automation",
        desc: "Connect your disparate software stack into fluid, automated business pipelines using Make, Zapier, n8n, and custom APIs.",
        deliverables: ["Event-Driven Workflows", "API Connectors", "Data Cleansing", "Operational Pipelines"],
      },
      {
        title: "Marketing Automation",
        route: "/ai-automation/marketing-automation",
        desc: "Automate lead capture, behavioral scoring, dynamic nurturing, and multi-channel campaign triggers.",
        deliverables: ["Lead Scoring", "Lifecycle Sequences", "Multi-Touch Nurturing", "Attribution Models"],
      },
      {
        title: "CRM Automation",
        route: "/ai-automation/crm-automation",
        desc: "Eliminate manual CRM updating with automatic contact enrichment, deal stage progression, and task reminders.",
        deliverables: ["HubSpot/Salesforce Sync", "Auto-Enrichment", "Pipeline Governance", "Sales Rep Alerts"],
      },
    ],
    process: [
      { step: "01", title: "Workflow & Friction Audit", desc: "We map your current business processes, identifying high-frequency repetitive tasks, error points, and API access requirements." },
      { step: "02", title: "Architecture & Security Protocol", desc: "We design secure system architectures ensuring your sensitive company and customer data remains private and protected." },
      { step: "03", title: "Development & Iterative Testing", desc: "We configure connectors, prompt architectures, RAG vector embeddings, and fallback error-handling logic." },
      { step: "04", title: "Deployment, Training & Monitoring", desc: "We deploy the automated pipelines, train your staff, and implement 24/7 telemetry to guarantee 99.9% uptime." },
    ],
    techStack: ["OpenAI / GPT-4o", "Anthropic Claude", "LangChain", "LlamaIndex", "n8n", "Make.com", "Zapier", "Python / FastAPI", "Pinecone / pgvector"],
    caseStudies: [
      { name: "BenchKart", category: "B2B Marketplace", summary: "Automated vendor matching and lead distribution workflows, cutting requirement processing time by 70%.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Agritech & Warehousing", summary: "Engineered automated data collection and inspection logging systems across agricultural warehouse facilities.", route: "/work/#staragri" },
      { name: "Cavalo", category: "Commercial Automotive", summary: "Implemented automated WhatsApp and CRM inquiry qualification and test-drive scheduling pipelines.", route: "/work/#cavalo" },
    ],
    faqs: [
      { question: "What is the difference between an AI chatbot and an AI agent?", answer: "A chatbot typically responds to user questions with informational text in a back-and-forth dialogue. An AI agent goes further: it has agency and tools to execute actions on your behalf—such as creating an invoice in your accounting tool, updating a deal in your CRM, sending an email confirmation, or querying a live database." },
      { question: "Will our proprietary company data be safe and private?", answer: "Yes, completely. We build enterprise-grade architectures that adhere to SOC 2 and GDPR principles. We use private API endpoints with zero-data-retention agreements so your internal company information is never used to train public AI models." },
      { question: "How much time can our team realistically save with AI automation?", answer: "On average, our clients reduce repetitive administrative tasks by 40% to 65%, freeing key team members to focus on high-value client relationships, strategic growth, and product innovation." },
    ],
  },
  "ai-agent-development": {
    slug: "ai-agent-development",
    route: "/ai-automation/ai-agent-development",
    parentRoute: "/ai-automation",
    parentLabel: "AI & Automation",
    title: "AI Agent Development Services | Autonomous Systems & Tool Use | SARS Global",
    eyebrow: "Autonomous AI Engineering",
    metaDescription: "Build production-grade autonomous AI agents with SARS Global. Multi-step reasoning, external tool-calling, custom API integrations, and robust enterprise guardrails.",
    heroHeadline: "Custom Autonomous AI Agents Engineered for Complex Operations",
    heroSubheadline: "Move beyond simple chatbots. We develop autonomous AI agents that analyze unstructured data, interact with your software tools, and independently complete complex business processes.",
    badges: ["Multi-Step Planning & Execution", "API Tool-Calling Capabilities", "Document & Data Extraction", "Human-in-the-Loop Safeguards", "Vector Search & Memory", "Enterprise Security & Privacy"],
    challenge: {
      title: "Why Traditional Rule-Based Bots Fall Short",
      description: "Static if-then scripts cannot handle real-world business ambiguity. When inputs vary slightly, traditional scripts break down, forcing human staff to manually intervene and solve exceptions.",
      points: [
        "Rigid automation scripts breaking on edge cases and unstructured text inputs",
        "Inability to synthesize information across multiple internal databases in real time",
        "High cost of maintaining complex brittle integration scripts across platforms",
        "Risk of model hallucinations without strict deterministic verification layers",
      ],
    },
    solutions: [
      {
        title: "Action-Oriented Agent Architectures",
        desc: "Agents configured with function calling and API access to interact directly with your ERP, CRM, database, and internal tools.",
        deliverables: ["Custom OpenAPI tool definitions", "Context-aware action selection", "Execution validation & schema enforcement", "Structured JSON output parsing"],
      },
      {
        title: "Intelligent Document Processing (IDP)",
        desc: "Agents that read invoices, contracts, technical specifications, and handwritten receipts, extracting structured data with 99%+ accuracy.",
        deliverables: ["Multi-modal vision and text parsing", "Table and line-item extraction", "Confidence scoring & flag thresholds", "Direct ERP ledger entry"],
      },
      {
        title: "Deterministic Guardrails & Verification",
        desc: "Layered verification frameworks that ensure the AI agent operates strictly within approved compliance boundaries and never hallucinates.",
        deliverables: ["Constitutional AI compliance rules", "PII detection and masking", "Prompt injection defense layers", "Escalation queues for human confirmation"],
      },
      {
        title: "Long-Term Memory & Context Retrieval",
        desc: "Stateful agent frameworks with episodic and semantic memory that recall historical interactions, past client preferences, and company policies.",
        deliverables: ["Vector database indexing (Pinecone/pgvector)", "Conversation history compression", "Role-based contextual awareness", "Real-time policy injection"],
      },
    ],
    process: [
      { step: "01", title: "Task Deconstruction & Tool Mapping", desc: "We analyze the target business task, break it down into atomic decisions, and define required software tools." },
      { step: "02", title: "Agent Framework & Prompt Engineering", desc: "We select the optimal model foundation, build reasoning prompts, and configure function execution schemas." },
      { step: "03", title: "Guardrails & Red-Teaming", desc: "We rigorously test edge cases, adversarial prompts, and system failures to guarantee rock-solid operational safety." },
      { step: "04", title: "Production Deployment & Observability", desc: "We deploy on private cloud infrastructure with full telemetry, latency tracking, and execution logging." },
    ],
    techStack: ["LangChain", "LangGraph", "OpenAI Assistants API", "Anthropic Claude 3.5 Sonnet", "FastAPI", "Pinecone", "Docker", "PostgreSQL"],
    caseStudies: [
      { name: "BenchKart", category: "B2B Tech", summary: "Deployed an intelligent matching agent that automatically matches enterprise RFP briefs to qualified vendor portfolios.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Agritech Operations", summary: "Engineered automated agricultural inspection verification agents processing daily warehouse reports.", route: "/work/#staragri" },
    ],
    faqs: [
      { question: "How do you prevent an AI agent from making costly mistakes?", answer: "We implement deterministic guardrails and 'human-in-the-loop' thresholds. For high-stakes operations (such as approving refunds, making bank transfers, or signing contracts), the agent compiles the work and drafts the action, but requires explicit human approval before executing." },
      { question: "What infrastructure do custom AI agents run on?", answer: "We deploy agents on your own private cloud environment (AWS, GCP, Azure) or our managed enterprise infrastructure, ensuring compliance with your corporate security policies." },
      { question: "Can an AI agent connect to our proprietary internal software?", answer: "Yes. As long as your internal software has an API, database interface, or webhook support, our team can write custom connectors allowing the agent to read and write data seamlessly." },
    ],
  },
  "ai-chatbot-development": {
    slug: "ai-chatbot-development",
    route: "/ai-automation/ai-chatbot-development",
    parentRoute: "/ai-automation",
    parentLabel: "AI & Automation",
    title: "AI Chatbot Development Services | RAG & Conversational AI | SARS Global",
    eyebrow: "Conversational AI Solutions",
    metaDescription: "Deploy intelligent, 24/7 customer service and sales chatbots with SARS Global. Retrieval-Augmented Generation (RAG) trained on your company knowledge base.",
    heroHeadline: "Intelligent AI Chatbots Trained on Your Company Knowledge",
    heroSubheadline: "Deliver instant, accurate answers and generate qualified leads around the clock. We build conversational AI assistants that resolve support tickets and schedule meetings without human intervention.",
    badges: ["Retrieval-Augmented Generation (RAG)", "24/7 Instant Support Resolution", "Omnichannel (Web, WhatsApp, Slack)", "CRM Lead Qualification", "Multi-Language Support", "Live Agent Handoff"],
    challenge: {
      title: "The Frustration of Dumb Decision-Tree Bots",
      description: "Users hate traditional chatbots that present rigid multiple-choice buttons and inevitably respond with 'I didn't understand that.' Modern consumers and business buyers expect intelligent, context-aware dialogue that solves their problems immediately.",
      points: [
        "Slow support response times during off-hours leading to frustrated customers and churn",
        "Support teams bogged down answering the same 20 repetitive questions all day",
        "High cost of maintaining 24/7 multi-shift support staff for simple inquiries",
        "Loss of high-intent website visitors who leave when their questions aren't answered instantly",
      ],
    },
    solutions: [
      {
        title: "RAG on Company Knowledge Bases",
        desc: "We connect the chatbot to your product documentation, FAQs, PDFs, and Notion docs, ensuring it answers only with verified company facts.",
        deliverables: ["Vector embedding pipeline", "Document chunking & semantic search", "Direct source citation in responses", "Automatic daily knowledge updates"],
      },
      {
        title: "Omnichannel Deployment",
        desc: "Deploy a consistent, intelligent assistant across your website, WhatsApp Business, Telegram, Slack, and email channels.",
        deliverables: ["Custom branded web chat widget", "Official WhatsApp Business Cloud API setup", "Slack/Teams internal employee bot", "Cross-channel conversation continuity"],
      },
      {
        title: "Automated Lead Qualification & Booking",
        desc: "The bot naturally asks qualifying questions, captures contact info, updates your CRM, and books discovery calls via Calendly or HubSpot.",
        deliverables: ["Custom qualification question logic", "Calendar booking integration", "Real-time CRM lead creation", "Instant Slack alerts for sales reps"],
      },
      {
        title: "Seamless Human Handoff",
        desc: "When an inquiry requires human touch or sensitive intervention, the bot smoothly transitions the conversation to your live team with full context.",
        deliverables: ["Zendesk, Intercom & Freshchat integration", "Sentiment analysis escalation triggers", "Full transcript summarization for agents", "Snooze and office-hours routing"],
      },
    ],
    process: [
      { step: "01", title: "Knowledge Ingestion & Curation", desc: "We gather and structure your company documentation, FAQs, product specs, and past support tickets." },
      { step: "02", title: "RAG Vector Architecture Setup", desc: "We index your content in high-speed vector databases and test response accuracy against hundreds of real queries." },
      { step: "03", title: "UI Customization & Integrations", desc: "We match the chat widget to your exact brand aesthetics and integrate with your CRM and messaging channels." },
      { step: "04", title: "Live Launch & Continuous Tuning", desc: "We analyze real user conversation logs, continuously expanding the bot's knowledge and refining answer precision." },
    ],
    techStack: ["OpenAI GPT-4o", "Pinecone", "LangChain", "Next.js", "Tailwind CSS", "WhatsApp Cloud API", "Zendesk API", "HubSpot API"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Launched a 24/7 WhatsApp AI Assistant that handles buyer inquiries, vehicle spec comparisons, and dealership routing.", route: "/work/#cavalo" },
      { name: "Cloudnine KnowMoms", category: "Healthcare Community", summary: "Developed an empathetic maternal wellness informational assistant providing verified expert medical guidance.", route: "/work/#cloudnine" },
    ],
    faqs: [
      { question: "Will the chatbot give incorrect or hallucinated answers?", answer: "No. We utilize strict Retrieval-Augmented Generation (RAG) with conservative confidence thresholds. If an answer cannot be grounded directly in your approved documentation, the bot transparently admits it and offers to connect the user with a human team member." },
      { question: "Can the chatbot speak multiple languages?", answer: "Yes. Our AI chatbots natively understand and respond fluently in over 50 languages—including English, Hindi, Spanish, French, German, and Arabic—automatically detecting the user's preferred language." },
      { question: "How difficult is it to embed on our website?", answer: "It takes less than 5 minutes. We provide a single lightweight JavaScript snippet or React component that embeds cleanly without impacting your site speed or Core Web Vitals." },
    ],
  },
  "workflow-automation": {
    slug: "workflow-automation",
    route: "/ai-automation/workflow-automation",
    parentRoute: "/ai-automation",
    parentLabel: "AI & Automation",
    title: "Enterprise Workflow Automation Services | Make, Zapier & Custom APIs | SARS Global",
    eyebrow: "Process Engineering & Integration",
    metaDescription: "Eliminate manual data entry and connect your business apps with SARS Global. Custom workflow automation using Make, n8n, Zapier, and custom serverless webhooks.",
    heroHeadline: "Connect Your Tech Stack with Intelligent Workflow Automation",
    heroSubheadline: "We build reliable, event-driven automated pipelines that sync data across your cloud apps, automate client onboarding, and execute complex business logic flawlessly.",
    badges: ["Make.com & n8n Integration", "Zapier Enterprise Workflows", "Custom REST & GraphQL Webhooks", "Zero-Data-Loss Architectures", "Multi-App Synchronization", "Automated Error Handling"],
    challenge: {
      title: "The Cost of Disconnected Business Tools",
      description: "Modern companies use an average of 15 to 30 software tools. When these platforms don't talk to each other, employees become human data bridges, leading to delays, missed customer follow-ups, and expensive data errors.",
      points: [
        "Inconsistent customer records across sales, billing, and fulfillment platforms",
        "Delays in processing orders, contracts, and new client onboarding checklists",
        "Fragile integrations built on basic Zapier accounts that silently fail without notification",
        "Key personnel spending hours manually downloading CSVs and uploading them to other tools",
      ],
    },
    solutions: [
      {
        title: "Cross-Platform Data Synchronization",
        desc: "Bi-directional or unidirectional real-time data sync between your CRM, ERP, accounting, inventory, and communication software.",
        deliverables: ["Two-way CRM to ERP sync", "Stripe and QuickBooks revenue matching", "Inventory and fulfillment order routing", "Automated deduplication logic"],
      },
      {
        title: "Client Onboarding & Project Kickoff",
        desc: "Trigger an entire sequence of events the moment a contract is signed in DocuSign or payment clears in Stripe.",
        deliverables: ["Automated Slack channel creation", "Google Drive/Notion folder provisioning", "Project management board template setup", "Welcome email and calendar link delivery"],
      },
      {
        title: "Document Generation & E-Sign Workflows",
        desc: "Automatically populate contracts, non-disclosure agreements, invoices, and proposals with dynamic CRM data.",
        deliverables: ["PandaDoc & DocuSign API automation", "Automated PDF invoice generation", "Signature tracking and notification alerts", "Signed agreement archiving to cloud storage"],
      },
      {
        title: "Automated Error Logging & Recovery",
        desc: "Enterprise-grade error handling with dead-letter queues, retry mechanisms, and instant incident alerts to your tech team.",
        deliverables: ["Zero-data-loss retry queues", "Slack/Teams exception notifications", "Automated fallback mechanisms", "Monthly workflow health audits"],
      },
    ],
    process: [
      { step: "01", title: "Process Mapping & Architecture", desc: "We map trigger events, conditional logic branches, data payloads, and target endpoints across your stack." },
      { step: "02", title: "Data Transformation & Logic Build", desc: "We build and test workflows in Make, n8n, or custom serverless code, handling JSON transformations and sanitization." },
      { step: "03", title: "Edge Case & Stress Testing", desc: "We simulate high payload spikes, API timeouts, and missing fields to ensure absolute operational stability." },
      { step: "04", title: "Deployment & Team Handoff", desc: "We put workflows live, document the integration architecture, and set up continuous automated monitoring." },
    ],
    techStack: ["Make.com", "n8n", "Zapier", "AWS Lambda", "Node.js", "PostgreSQL", "Google Workspace APIs", "Stripe API"],
    caseStudies: [
      { name: "BenchKart", category: "B2B Marketplace", summary: "Automated end-to-end buyer inquiry distribution, NDA generation, and vendor notifications via custom webhook pipelines.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Logistics & Warehousing", summary: "Synchronized warehouse intake data across legacy systems and modern reporting dashboards in real time.", route: "/work/#staragri" },
    ],
    faqs: [
      { question: "Why use Make or n8n instead of simple Zapier?", answer: "While Zapier is fine for basic 2-step tasks, platforms like Make and self-hosted n8n support complex data arrays, nested logic routers, custom error handlers, and lower transactional pricing, making them far superior for enterprise operations." },
      { question: "What happens if one of our cloud software tools goes down?", answer: "We build our automations with retry queues and fallback alerts. If an endpoint is temporarily unreachable, the automation pauses that payload and retries exponentially, notifying your team without dropping any critical business data." },
      { question: "Can you automate workflows involving legacy or on-premise software?", answer: "Yes. Using custom API adapters, SFTP watchers, or webhook gateways, we routinely connect modern cloud platforms to legacy ERPs, databases, and on-premise servers." },
    ],
  },
  "marketing-automation": {
    slug: "marketing-automation",
    route: "/ai-automation/marketing-automation",
    parentRoute: "/ai-automation",
    parentLabel: "AI & Automation",
    title: "Marketing Automation Services | Email, Lead Scoring & Funnels | SARS Global",
    eyebrow: "Demand Generation & Lifecycle Automation",
    metaDescription: "Accelerate pipeline velocity with SARS Global's marketing automation services: behavioral lead scoring, personalized email sequences, and lifecycle nurturing.",
    heroHeadline: "Automate Demand Generation and Accelerate Deal Velocity",
    heroSubheadline: "Deliver the right message to the right prospect at the exact right moment. We build intelligent marketing automation engines that nurture prospects from initial click to closed deal.",
    badges: ["Behavioral Lead Scoring", "Automated Email Sequences", "Multi-Touch Lifecycle Marketing", "Dynamic Content Personalization", "HubSpot & ActiveCampaign Setup", "Closed-Loop Attribution"],
    challenge: {
      title: "Why Inbound Leads Go Cold",
      description: "Studies show that leads contacted within 5 minutes are 21 times more likely to enter the sales cycle than those contacted after 30 minutes. When lead qualification and follow-up rely on manual human review, valuable opportunities slip away.",
      points: [
        "Inbound leads waiting hours or days for an initial response from sales",
        "Blasting the entire email list with identical messages rather than segmented relevant content",
        "Lack of behavioral tracking indicating when a dormant prospect re-engages with high-intent pages",
        "Sales reps wasting time following up with unqualified, low-budget tire-kickers",
      ],
    },
    solutions: [
      {
        title: "Behavioral Lead Scoring",
        desc: "Automatically assign point values based on website page visits, email clicks, form submissions, and company firmographics.",
        deliverables: ["Demographic & firmographic scoring models", "Behavioral decay algorithms", "MQL (Marketing Qualified Lead) threshold triggers", "Instant rep alerts on high-intent behaviors"],
      },
      {
        title: "Automated Email Nurture Journeys",
        desc: "Dynamic, conditional email sequences tailored to the recipient's industry, role, pain points, and current funnel position.",
        deliverables: ["Welcome & onboarding email drip series", "Cold lead re-engagement triggers", "Industry-specific educational funnels", "Post-demo follow-up and proof sequences"],
      },
      {
        title: "Instant Lead Routing & SLA Governance",
        desc: "Route qualified leads immediately to the right account executive based on geography, deal size, or vertical specialization.",
        deliverables: ["Round-robin sales distribution logic", "5-minute response SLA tracking", "Automated SMS/WhatsApp alerts to reps", "Instant calendar booking confirmation"],
      },
      {
        title: "Marketing & Sales Alignment Dashboards",
        desc: "Unified reporting showing exactly which marketing campaigns generated pipeline, deals, and closed-won revenue.",
        deliverables: ["Lead status lifecycle reporting", "Email engagement and deliverability metrics", "First-touch, last-touch & multi-touch attribution", "Executive ROI presentations"],
      },
    ],
    process: [
      { step: "01", title: "Funnel & Lifecycle Mapping", desc: "We define your lead stages (Subscriber, Lead, MQL, SQL, Opportunity, Customer) and qualification criteria." },
      { step: "02", title: "Platform Configuration & Cleansing", desc: "We configure your marketing automation platform, clean contact databases, and set up tracking pixels." },
      { step: "03", title: "Sequence Copywriting & Asset Build", desc: "Our direct-response copywriters draft personalized email sequences and dynamic landing page workflows." },
      { step: "04", title: "Testing, Launch & Optimization", desc: "We test all branch logic, verify deliverability and SPF/DKIM records, launch, and monitor open/reply metrics." },
    ],
    techStack: ["HubSpot Marketing Hub", "ActiveCampaign", "Klaviyo", "Customer.io", "Brevo", "Google Analytics 4", "Zapier"],
    caseStudies: [
      { name: "Cavalo", category: "Automotive", summary: "Built multi-touch lead nurturing campaigns that re-engaged dormant vehicle buyers and scheduled dealership visits.", route: "/work/#cavalo" },
      { name: "Avance Consulting", category: "Staffing & Recruitment", summary: "Automated candidate application confirmations, interview reminders, and recruiter talent matching.", route: "/work/#avance-consulting" },
    ],
    faqs: [
      { question: "Which marketing automation software do you recommend?", answer: "For B2B companies, we primarily recommend HubSpot or ActiveCampaign due to their robust lead scoring and CRM alignment. For eCommerce brands, Klaviyo is typically the strongest choice. We also work with Marketo, Pardot, and Brevo." },
      { question: "Will automated emails damage our domain sender reputation?", answer: "No, because we implement best-practice deliverability protocols. We configure SPF, DKIM, and DMARC DNS records, warm up new sender domains gradually, and enforce list hygiene so bounce rates remain well under 1%." },
      { question: "How does marketing automation improve sales team close rates?", answer: "It ensures sales reps only spend time on qualified buyers who have demonstrated buying interest, while providing them with full context on which pages, case studies, and emails the prospect viewed." },
    ],
  },
  "crm-automation": {
    slug: "crm-automation",
    route: "/ai-automation/crm-automation",
    parentRoute: "/ai-automation",
    parentLabel: "AI & Automation",
    title: "CRM Automation Services | HubSpot, Salesforce & Zoho | SARS Global",
    eyebrow: "Sales Operations & Pipeline Automation",
    metaDescription: "Eliminate manual CRM updating and enforce sales hygiene. SARS Global automates pipeline stages, contact enrichment, and task reminders in HubSpot, Salesforce, and Zoho.",
    heroHeadline: "Turn Your CRM into an Autonomous Sales Machine",
    heroSubheadline: "Free your sales team from hours of manual data entry. We automate contact enrichment, deal stage movements, task reminders, and executive reporting across HubSpot, Salesforce, and Zoho.",
    badges: ["HubSpot CRM Architecture", "Salesforce Flow Automation", "Zoho CRM Customization", "Automated Contact Enrichment", "Pipeline Hygiene & Governance", "Sales Activity Tracking"],
    challenge: {
      title: "Why Sales Reps Hate Using the CRM",
      description: "When sales reps must manually log every phone call, update contact details, and advance deal stages, they cut corners. As a result, pipeline forecasts become unreliable and management loses visibility into genuine sales health.",
      points: [
        "Sales reps spending 5+ hours per week on manual CRM data entry instead of selling",
        "Stale deals cluttering pipeline views with no active follow-up tasks scheduled",
        "Missing contact phone numbers, LinkedIn profiles, and verified job titles",
        "Inaccurate revenue forecasting caused by outdated deal close dates and probabilities",
      ],
    },
    solutions: [
      {
        title: "Automated Contact & Company Enrichment",
        desc: "Automatically enrich incoming leads with verified company headcount, industry, annual revenue, and LinkedIn profiles.",
        deliverables: ["Clearbit, Apollo & ZoomInfo integrations", "Real-time email verification & validation", "Firmographic data appending", "Automatic lead categorization"],
      },
      {
        title: "Deal Stage & Pipeline Governance",
        desc: "Automate deal progression based on verified actions—such as proposal viewing, contract signing, or meeting completion.",
        deliverables: ["Automated deal stage advancement rules", "Required property enforcement per stage", "Stale deal escalation and auto-closing rules", "Probability and close date recalibration"],
      },
      {
        title: "Sales Rep Task & Follow-up Triggers",
        desc: "Ensure zero deals slip through the cracks by automatically creating prioritized task queues and follow-up reminders.",
        deliverables: ["Next-step task automation on deal updates", "Slack reminders for upcoming meetings", "Meeting summary and action item auto-logging", "Manager alerts on uncontacted leads"],
      },
      {
        title: "Executive Forecasting & Performance Dashboards",
        desc: "Custom reporting giving executive leadership real-time visibility into quota attainment, pipeline velocity, and conversion rates.",
        deliverables: ["Weighted pipeline revenue forecasts", "Sales rep activity and conversion scorecards", "Win/loss reason analysis dashboards", "Automated weekly executive email summaries"],
      },
    ],
    process: [
      { step: "01", title: "Sales Process & Pipeline Audit", desc: "We interview your sales leaders and reps to map your genuine sales cycle and identify friction points." },
      { step: "02", title: "Data Schema & Property Modeling", desc: "We standardize custom properties, deal stages, and lifecycle rules to ensure data consistency." },
      { step: "03", title: "Automation & Flow Development", desc: "We build automated workflows, task assignment rules, and third-party data enrichment connectors." },
      { step: "04", title: "Testing, User Training & Rollout", desc: "We validate every automation in a sandbox, train your sales reps, and monitor pipeline adoption." },
    ],
    techStack: ["HubSpot CRM", "Salesforce Sales Cloud", "Zoho CRM", "Pipedrive", "Apollo.io", "Make.com", "Slack API"],
    caseStudies: [
      { name: "Avance Consulting", category: "Executive Search", summary: "Automated candidate pipeline workflows and client hiring requirement status updates in their recruitment CRM.", route: "/work/#avance-consulting" },
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Synchronized dealership lead flows across territory managers with automated call logging and test-drive follow-up tasks.", route: "/work/#cavalo" },
    ],
    faqs: [
      { question: "Can you fix a messy, cluttered CRM with duplicate data?", answer: "Yes. We frequently conduct CRM cleanups: merging duplicates, archiving dead contacts, standardizing custom properties, and putting governance rules in place so your data remains clean moving forward." },
      { question: "Which CRM platforms do you support?", answer: "We specialize in HubSpot, Salesforce, Zoho CRM, and Pipedrive. We also build custom database integrations for proprietary in-house CRMs." },
      { question: "How long does a typical CRM automation project take?", answer: "Most standard CRM optimization and automation projects are completed within 3 to 6 weeks, including data modeling, automation build, testing, and team training." },
    ],
  },
};
