import { ServiceData } from "./types";

export const DIGITAL_MARKETING_SERVICES: Record<string, ServiceData> = {
  "hub": {
    slug: "digital-marketing",
    route: "/digital-marketing",
    title: "Digital Marketing Services | SEO, Paid Media & Growth | SARS Global",
    eyebrow: "Growth & Performance Marketing",
    metaDescription: "Drive predictable business growth with SARS Global's full-funnel digital marketing services: organic SEO, Google Ads, performance paid media, social media, and content marketing.",
    heroHeadline: "Full-Funnel Digital Marketing Built for Revenue Growth",
    heroSubheadline: "We combine intent-driven SEO, high-efficiency performance marketing, data analytics, and compelling brand storytelling to generate qualified demand and scalable enterprise customer acquisition.",
    badges: ["Organic Search (SEO)", "Google Ads & PPC", "Performance Marketing", "Social Media Marketing", "Content Strategy", "Conversion Rate Optimization"],
    challenge: {
      title: "The Reality of Modern Digital Acquisition",
      description: "Ad platform algorithms are increasingly automated, ad costs per lead continue to rise, and consumer attention is fragmented across dozens of touchpoints. Surface-level vanity metrics like impressions and clicks no longer correlate with company profitability.",
      points: [
        "Rising cost-per-click across Google and Meta ad auctions",
        "Disjointed attribution between top-of-funnel campaigns and bottom-line revenue",
        "Search algorithm shifts prioritizing deep contextual authority and brand search volume",
        "Wasted ad spend on low-intent clicks due to unrefined funnel architectures",
      ],
    },
    solutions: [
      {
        title: "Search Engine Optimization (SEO)",
        desc: "End-to-end technical, on-page, and authority SEO that positions your brand at the exact moment prospects are actively searching for your solutions.",
        deliverables: ["Technical site audits & Core Web Vitals", "Keyword intent architecture & topic clustering", "High-authority editorial link acquisition", "Local SEO & multi-location map rankings"],
      },
      {
        title: "Performance & Paid Media",
        desc: "Precision paid campaigns across Google Search, YouTube, LinkedIn, Meta, and Programmatic networks optimized strictly for customer acquisition cost (CAC).",
        deliverables: ["Full-funnel audience segmentation", "High-converting ad creative & video production", "Rigorous A/B split testing methodology", "Real-time revenue attribution & ROAS tracking"],
      },
      {
        title: "Social Media Marketing",
        desc: "Strategic organic and paid social distribution that turns passive scrollers into engaged brand advocates and qualified sales conversations.",
        deliverables: ["Platform-specific editorial content", "Motion graphic & short-form video creative", "Executive thought leadership programs", "Community management & conversation funnels"],
      },
      {
        title: "Content & Funnel Strategy",
        desc: "Educational, high-intent assets—whitepapers, case studies, conversion landing pages, and email nurture workflows—that guide prospects through complex buyer journeys.",
        deliverables: ["Customer journey & persona research", "Long-form editorial pillar content", "Interactive ROI calculators & lead magnets", "Automated email lifecycle sequences"],
      },
    ],
    subServices: [
      {
        title: "SEO Services",
        route: "/digital-marketing/seo-services",
        desc: "Comprehensive search engine optimization for sustainable organic search visibility, qualified organic traffic, and domain authority.",
        deliverables: ["Technical SEO", "Topic Clusters", "On-Page Optimization", "Authority Building"],
      },
      {
        title: "Performance Marketing",
        route: "/digital-marketing/performance-marketing",
        desc: "Data-led media buying across Meta, Google, and programmatic channels engineered around customer lifetime value and lower CAC.",
        deliverables: ["Paid Acquisition", "Retargeting", "CAC Optimization", "ROAS Tracking"],
      },
      {
        title: "Google Ads (PPC)",
        route: "/digital-marketing/google-ads",
        desc: "Search, Display, Shopping, and Performance Max campaigns designed to intercept high-intent buyer searches with surgical bid precision.",
        deliverables: ["Search Ads", "PMax Campaigns", "Negative Keyword Control", "Landing Page CRO"],
      },
      {
        title: "Social Media Marketing",
        route: "/digital-marketing/social-media-marketing",
        desc: "Build an unmistakable digital presence across LinkedIn, Instagram, and YouTube with consistent brand voice and creative production.",
        deliverables: ["Organic Social", "Brand Storytelling", "Reels & Shorts Production", "Executive Branding"],
      },
      {
        title: "Content Marketing",
        route: "/digital-marketing/content-marketing",
        desc: "Authoritative, research-backed content assets that demonstrate subject matter expertise, answer buyer objections, and drive conversions.",
        deliverables: ["Content Strategy", "Pillar Articles", "E-books & Guides", "Lead Magnets"],
      },
    ],
    process: [
      { step: "01", title: "Market & Funnel Audit", desc: "We analyze your current channel economics, conversion bottlenecks, competitor positioning, and audience search behavior." },
      { step: "02", title: "Channel & Unit Economics Strategy", desc: "We model budget allocation across search intent, paid discovery, and organic compounding based on target CAC and payback windows." },
      { step: "03", title: "Campaign & Asset Production", desc: "Our creative, copywriting, and engineering teams build landing pages, ad variations, tracking schemas, and SEO content." },
      { step: "04", title: "Continuous Optimization & Scaling", desc: "Weekly sprint cycles analyze performance data, prune non-performing segments, and aggressively scale high-ROAS channels." },
    ],
    techStack: ["Google Ads", "Meta Ads Manager", "LinkedIn Campaign Manager", "Google Analytics 4", "Semrush", "Ahrefs", "Google Search Console", "Looker Studio"],
    caseStudies: [
      { name: "Cavalo", category: "Automotive & Commercial", summary: "Scaled digital acquisition and nationwide buyer inquiries through targeted Google Search, Meta Ads, and video production.", route: "/work/#cavalo" },
      { name: "Cloudnine KnowMoms", category: "Healthcare", summary: "Crafted sensitive, engaging healthcare content and social campaigns building brand trust across thousands of families.", route: "/work/#cloudnine" },
      { name: "BenchKart", category: "B2B Tech Marketplace", summary: "Built organic inbound channels and optimized landing pages to capture enterprise technology procurement demand.", route: "/work/#benchkart" },
    ],
    faqs: [
      { question: "How does SARS Global measure digital marketing success?", answer: "We focus strictly on commercial outcomes: qualified pipeline, cost per acquisition (CPA/CAC), customer conversion rate, and blended return on ad spend (ROAS). We connect top-of-funnel campaign data with CRM pipeline stages so you have clear visibility into revenue contribution." },
      { question: "How soon can we expect results from SEO vs. Paid Advertising?", answer: "Paid advertising generates qualified traffic and lead volume within days of launch. Search engine optimization is a compounding asset that generally shows measurable indexing and ranking gains within 60-90 days, delivering long-term lower customer acquisition costs over 6-12 months." },
      { question: "Do you provide creative assets, landing pages, and ad copy?", answer: "Yes. SARS Global provides full-service execution. Our in-house creative production, copywriting, and development teams build conversion-optimized landing pages, static creatives, short-form video reels, and responsive ad variants tailored to each channel." },
    ],
  },
  "seo-services": {
    slug: "seo-services",
    route: "/digital-marketing/seo-services",
    parentRoute: "/digital-marketing",
    parentLabel: "Digital Marketing",
    title: "Enterprise SEO Services | Organic Search & Technical Optimization | SARS Global",
    eyebrow: "Search Engine Optimization",
    metaDescription: "Drive compounding organic revenue with SARS Global's expert SEO services: technical site audits, Core Web Vitals, keyword intent mapping, and authority building.",
    heroHeadline: "Technical & Intent-Driven SEO That Ranks and Converts",
    heroSubheadline: "We engineer organic search engines to become your most profitable customer acquisition channel through semantic architecture, technical excellence, and authoritative industry content.",
    badges: ["Technical Site Architecture", "Core Web Vitals Optimization", "Keyword Intent Mapping", "Topic Clusters", "Authoritative Backlinks", "Schema & Structured Data"],
    challenge: {
      title: "Why Most SEO Campaigns Fail to Generate Revenue",
      description: "Traditional SEO agencies focus on raw keyword rankings rather than commercial search intent. Ranking for high-volume informational queries does not help your business unless those visitors can be converted into paying accounts.",
      points: [
        "Focusing on high-volume, low-intent vanity keywords that never convert",
        "Technical site bloat, slow page load speeds, and poor Core Web Vitals",
        "Shallow, duplicate, or unhelpful AI-spun content penalized by modern search updates",
        "Lack of internal linking architecture preventing Google from establishing topical depth",
      ],
    },
    solutions: [
      {
        title: "Technical SEO & Architecture",
        desc: "Full crawl analysis, indexation audit, canonicalization, mobile responsiveness, and Core Web Vitals enhancement.",
        deliverables: ["Render budget optimization", "Structured data & Schema.org markup", "XML sitemap & robots.txt governance", "URL architecture & redirect cleanup"],
      },
      {
        title: "Semantic Content & Topic Clusters",
        desc: "Develop comprehensive pillar content and supporting spoke articles that demonstrate unambiguous subject matter authority to search engines.",
        deliverables: ["Buyer intent search mapping", "Competitive gap analysis", "Comprehensive pillar page creation", "Content refresh & optimization sprints"],
      },
      {
        title: "Digital PR & Editorial Authority",
        desc: "Earn high-value, contextual backlinks from reputable industry publications, trade journals, and digital media.",
        deliverables: ["Original industry survey research", "Thought leadership commentary", "Unlinked brand mention reclamation", "High-DA contextual link acquisition"],
      },
      {
        title: "Local & Multi-Location SEO",
        desc: "Dominate local map packs and high-intent localized search queries for brick-and-mortar and regional service businesses.",
        deliverables: ["Google Business Profile optimization", "Local citation audits & consistency", "Geo-targeted landing pages", "Local review generation workflows"],
      },
    ],
    process: [
      { step: "01", title: "Comprehensive Deep Audit", desc: "We evaluate 120+ technical checkpoints, indexation health, existing backlink profile, and competitor market share." },
      { step: "02", title: "Keyword & Entity Architecture", desc: "We map high-intent commercial keywords and semantic entities to your primary product, service, and solution pages." },
      { step: "03", title: "On-Page & Technical Remediation", desc: "Our engineering and editorial teams resolve technical blockers, implement structured data, and optimize page content." },
      { step: "04", title: "Authority Building & Reporting", desc: "We deploy proactive editorial link acquisition while monitoring keyword rankings, search impressions, and organic conversions." },
    ],
    techStack: ["Google Search Console", "Ahrefs", "Semrush", "Screaming Frog", "Sitebulb", "PageSpeed Insights", "Looker Studio"],
    caseStudies: [
      { name: "Avance Consulting", category: "Talent Solutions", summary: "Revamped site architecture and structured career pages to capture national recruitment and executive search traffic.", route: "/work/#avance-consulting" },
      { name: "BenchKart", category: "B2B Marketplace", summary: "Targeted enterprise software procurement keywords, resulting in substantial organic lead volume.", route: "/work/#benchkart" },
    ],
    faqs: [
      { question: "What is the difference between technical SEO and content SEO?", answer: "Technical SEO ensures search engines can efficiently crawl, render, index, and understand your website without friction or speed penalties. Content SEO ensures your pages satisfy user intent with comprehensive, trustworthy answers that earn high rankings and conversions." },
      { question: "How long does it take for SEO changes to impact Google rankings?", answer: "Technical fixes often register within 2 to 4 weeks. Meaningful ranking increases for competitive commercial queries typically develop between months 2 and 4 as Google re-crawls and re-indexes your content and recognizes topical authority." },
      { question: "Do you follow Google's Webmaster & Search Quality Guidelines?", answer: "Yes, strictly. We employ 100% white-hat methodologies compliant with Google's helpful content guidelines, spam policies, and webmaster standards." },
    ],
  },
  "performance-marketing": {
    slug: "performance-marketing",
    route: "/digital-marketing/performance-marketing",
    parentRoute: "/digital-marketing",
    parentLabel: "Digital Marketing",
    title: "Performance Marketing Services | Paid Media & CAC Optimization | SARS Global",
    eyebrow: "Paid Media & Growth",
    metaDescription: "Scale revenue with precision media buying. SARS Global builds high-ROAS performance marketing funnels across Meta, Google, LinkedIn, and YouTube.",
    heroHeadline: "Data-Driven Performance Marketing That Maximizes ROAS",
    heroSubheadline: "We engineer profitable paid customer acquisition machines by combining granular audience targeting, high-velocity creative testing, and rigorous unit-economics management.",
    badges: ["Full-Funnel Paid Strategy", "Meta Ads (Facebook & Instagram)", "Google Ads & YouTube", "LinkedIn B2B Media Buying", "Creative Testing Framework", "ROAS & CAC Optimization"],
    challenge: {
      title: "Overcoming Rising Ad Costs & Attribution Blindness",
      description: "Privacy updates, automated bidding systems, and ad fatigue have degraded standard agency playbook performance. Without specialized creative testing and reliable attribution, ad budgets get wasted quickly.",
      points: [
        "Unpredictable ad performance caused by relying on single 'silver-bullet' ad creatives",
        "Inaccurate conversion tracking and attribution loss after iOS privacy changes",
        "Generic ad creatives that fail to hook target prospects in their first 3 seconds",
        "Disconnection between lead volume and sales team qualification rates",
      ],
    },
    solutions: [
      {
        title: "Omnichannel Paid Media Architecture",
        desc: "Seamless integration across Google Search, Meta Ads, YouTube, and LinkedIn that targets buyers at each phase of awareness.",
        deliverables: ["Top-of-funnel demand generation", "Middle-of-funnel proof & consideration", "Bottom-of-funnel intent capture & retargeting", "Customer win-back & upsell loops"],
      },
      {
        title: "High-Velocity Creative Testing",
        desc: "Systematic production and testing of visual hooks, copy angles, problem-aware narratives, and value-proposition framing.",
        deliverables: ["Short-form video ads (UGC & brand motion)", "High-contrast static banners & carousels", "Direct-response copywriting", "Weekly creative win/loss analysis"],
      },
      {
        title: "Conversion Rate Optimization (CRO)",
        desc: "Custom dedicated landing pages designed specifically for each ad campaign to maximize visitor-to-lead conversion rates.",
        deliverables: ["Message-matched landing page development", "Form length & friction reduction", "Heatmap & user session analysis", "Split testing headlines & CTAs"],
      },
      {
        title: "Server-Side Tracking & Analytics",
        desc: "First-party data infrastructure using Google Tag Manager Server-Side and Meta Conversions API (CAPI) for accurate attribution.",
        deliverables: ["Meta Conversions API (CAPI) setup", "Enhanced conversions for Google Ads", "Custom CRM revenue attribution modeling", "Automated executive ROAS dashboards"],
      },
    ],
    process: [
      { step: "01", title: "Attribution & Unit Economics Setup", desc: "We configure server-side tracking, establish target CAC thresholds, and map customer payback models." },
      { step: "02", title: "Creative Sprint & Funnel Build", desc: "Our team produces 10-20 distinct ad creative angles and pairs them with high-converting dedicated landing pages." },
      { step: "03", title: "Controlled Testing Phase", desc: "We run budget-capped test campaigns to identify winning hooks, copy frameworks, and audience clusters." },
      { step: "04", title: "Aggressive Scale & Budget Allocation", desc: "We shift budget to proven winners, expanding lookalikes and broad targeting while continuously iterating new creative variations." },
    ],
    techStack: ["Meta Ads Manager", "Google Ads", "LinkedIn Campaign Manager", "Meta CAPI", "Google Tag Manager Server-Side", "Triple Whale", "Looker Studio"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Scaled targeted Meta and Google campaigns across multiple territories, driving verified dealership buyers.", route: "/work/#cavalo" },
      { name: "Sri Khelari Builders", category: "Real Estate", summary: "Generated qualified property investor leads with hyper-local geo-targeted paid social and search ads.", route: "/work/#sri-khelari-builders" },
    ],
    faqs: [
      { question: "What budget do we need to start performance marketing?", answer: "While minimum testing budgets vary by industry and ticket size, we generally recommend a starting media spend of at least $1,500 to $3,000 per month so the ad algorithms have sufficient conversion data to train and optimize effectively." },
      { question: "How do you prevent ad fatigue?", answer: "We operate on bi-weekly creative sprint cycles. By systematically producing and cycling new video hooks, static creative variations, and copy angles, we keep ad frequency healthy and costs per acquisition stable." },
      { question: "Do you manage both the ad campaigns and the landing pages?", answer: "Yes. In our experience, optimizing ads without optimizing the post-click landing page experience yields subpar results. We design, host, and test high-converting landing pages as part of our core performance marketing service." },
    ],
  },
  "google-ads": {
    slug: "google-ads",
    route: "/digital-marketing/google-ads",
    parentRoute: "/digital-marketing",
    parentLabel: "Digital Marketing",
    title: "Google Ads Management Services | Search, PMax & PPC | SARS Global",
    eyebrow: "Pay-Per-Click Advertising",
    metaDescription: "Maximize ROI on Google Ads with SARS Global. Precision Google Search, Performance Max, Display, and YouTube campaigns managed by certified PPC specialists.",
    heroHeadline: "Google Ads Campaigns Engineered for Commercial ROI",
    heroSubheadline: "Capture high-intent buyers at the precise moment they search for your services. We eliminate wasted budget with negative keyword sculpting, smart bidding, and conversion-optimized landing pages.",
    badges: ["Google Search Ads", "Performance Max (PMax)", "Display & Remarketing", "YouTube Video Ads", "Negative Keyword Architecture", "Smart Bidding Optimization"],
    challenge: {
      title: "Why Most Google Ads Accounts Waste 30-50% of Their Budget",
      description: "Google's default account settings are heavily weighted toward maximizing Google's revenue, not yours. Broad match keywords, unchecked search partner networks, and poorly audited automated campaigns quietly drain budget.",
      points: [
        "Uncontrolled broad match search terms burning ad dollars on irrelevant queries",
        "Performance Max campaigns serving primarily on low-intent mobile display networks",
        "Generic ad copy with low Quality Scores resulting in artificially high cost-per-click",
        "Landing pages that don't match specific search keywords, driving high bounce rates",
      ],
    },
    solutions: [
      {
        title: "Search Network Precision",
        desc: "Surgically organized campaign structures with tight single-theme ad groups, deep negative keyword lists, and exact commercial intent matching.",
        deliverables: ["Commercial intent keyword mapping", "Comprehensive negative keyword libraries", "Responsive Search Ad (RSA) copy variations", "Ad extension & asset optimization"],
      },
      {
        title: "Performance Max (PMax) Management",
        desc: "Properly configured PMax campaigns with custom asset groups, first-party audience signals, and brand exclusion lists.",
        deliverables: ["Audience signal curation (CRM & website lists)", "Custom high-resolution creative assets", "Placement exclusion scripts", "URL expansion rule governance"],
      },
      {
        title: "YouTube & Video Action Campaigns",
        desc: "Engaging video ads that introduce your brand value proposition to target audiences and drive direct inbound inquiries.",
        deliverables: ["Direct-response video scriptwriting", "Visual hook editing for 5-second skip threshold", "In-market audience targeting", "Cross-device conversion tracking"],
      },
      {
        title: "Conversion Tracking & Bidding Strategy",
        desc: "Flawless tracking setup leveraging Enhanced Conversions and value-based bidding (tROAS / tCPA) aligned with sales team margins.",
        deliverables: ["Google Ads Enhanced Conversions", "Offline conversion import from CRM", "Target CPA and Target ROAS calibration", "Weekly search term audits and pruning"],
      },
    ],
    process: [
      { step: "01", title: "Historical Account & Competitor Audit", desc: "We identify keyword waste, Quality Score deficiencies, and competitor bid strategy opportunities." },
      { step: "02", title: "Campaign Restructure & Negative Lists", desc: "We rebuild campaign architecture into clean thematic clusters and implement defensive negative keyword frameworks." },
      { step: "03", title: "Landing Page & Tracking Alignment", desc: "We ensure conversion tracking verifies real business value and landing pages match search query intent exactly." },
      { step: "04", title: "Algorithmic Bidding Optimization", desc: "We guide Google's Smart Bidding algorithms with verified first-party conversion data to capture maximum margin." },
    ],
    techStack: ["Google Ads", "Google Tag Manager", "Google Analytics 4", "Google Ads Editor", "Semrush Keyword Magic", "Looker Studio"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Generated high-ticket commercial vehicle inquiries through surgical Google Search Ads and exact-match keyword groups.", route: "/work/#cavalo" },
      { name: "Avance Consulting", category: "Global Talent", summary: "Attracted corporate recruiting contracts via targeted search ads targeting enterprise workforce keywords.", route: "/work/#avance-consulting" },
    ],
    faqs: [
      { question: "What is Google Ads Quality Score and why does it matter?", answer: "Quality Score is Google's diagnostic rating (1 to 10) of how relevant your ad, keyword, and landing page are to the searcher. A high Quality Score earns lower cost-per-click (CPC) and higher ad positions, effectively multiplying the purchasing power of your budget." },
      { question: "Do you manage existing Google Ads accounts or only build new ones?", answer: "We do both. We can perform a comprehensive audit and restructure of your existing account, or build a clean new account architecture from the ground up." },
      { question: "Who owns the Google Ads account and data?", answer: "You do. You retain 100% ownership of your Google Ads account, campaign history, billing settings, and data at all times. SARS Global manages the account through our official Google Partner Manager." },
    ],
  },
  "social-media-marketing": {
    slug: "social-media-marketing",
    route: "/digital-marketing/social-media-marketing",
    parentRoute: "/digital-marketing",
    parentLabel: "Digital Marketing",
    title: "Social Media Marketing & Brand Creative | SARS Global",
    eyebrow: "Social & Brand Growth",
    metaDescription: "Build brand equity and engaged communities. SARS Global delivers social media strategy, video creative, reels, and executive thought leadership.",
    heroHeadline: "Social Media Strategy That Builds Trust and Drives Pipeline",
    heroSubheadline: "We transform social channels from vanity posting into high-impact brand awareness and lead generation engines with premium design, compelling video, and audience-first narratives.",
    badges: ["LinkedIn Thought Leadership", "Instagram & Reels Production", "YouTube Video Marketing", "Brand Identity & Voice", "Community Engagement", "Paid Social Distribution"],
    challenge: {
      title: "The Problem with Generic Social Media Posting",
      description: "Posting generic stock graphics and motivational quotes creates zero business value. Algorithms reward original perspectives, native short-form video, and genuine industry insights that solve user problems.",
      points: [
        "Inconsistent posting cadence leading to algorithmic reach penalties",
        "Low visual fidelity that dilutes brand authority in competitive markets",
        "Lack of native video formats (Reels, YouTube Shorts, LinkedIn Carousels)",
        "No clear conversion path from social followers to active business inquiries",
      ],
    },
    solutions: [
      {
        title: "Content Strategy & Editorial Calendar",
        desc: "Custom content pillars aligned with your business milestones, industry trends, and prospect pain points.",
        deliverables: ["Monthly content calendar & themes", "Platform-specific copy adaptation", "Tone of voice documentation", "Competitor positioning analysis"],
      },
      {
        title: "Creative Production & Short-Form Video",
        desc: "In-house graphic design, motion design, and video editing engineered for maximum platform engagement.",
        deliverables: ["Vertical video production (Reels & Shorts)", "Branded carousel templates", "Custom iconography and visual assets", "High-contrast hook design"],
      },
      {
        title: "Executive & Founder Branding",
        desc: "Position your leadership team as authoritative voices in your sector on LinkedIn and industry platforms.",
        deliverables: ["Executive profile optimization", "Weekly thought leadership post writing", "Industry commentary curation", "Key stakeholder network expansion"],
      },
      {
        title: "Community Management & Lead Routing",
        desc: "Active monitoring and engagement that converts comments and direct messages into qualified sales opportunities.",
        deliverables: ["Rapid response comment moderation", "Inbound DM qualification scripts", "FAQ knowledge base alignment", "Monthly engagement & audience analytics"],
      },
    ],
    process: [
      { step: "01", title: "Brand Voice & Audience Discovery", desc: "We define your brand's unique point of view, audience demographics, and target engagement formats." },
      { step: "02", title: "Visual Identity & Template Creation", desc: "Our creative team builds high-fidelity design templates, typography standards, and motion guidelines." },
      { step: "03", title: "Batch Production & Approval", desc: "We produce and review content in structured monthly sprints with complete collaborative approval." },
      { step: "04", title: "Publishing, Engagement & Reporting", desc: "We handle scheduling, real-time community engagement, and detailed analytics on reach, saves, and conversions." },
    ],
    techStack: ["Adobe Premiere Pro", "After Effects", "Figma", "Canva Pro", "Buffer", "Hootsuite", "Sprout Social", "Meta Business Suite"],
    caseStudies: [
      { name: "Cloudnine KnowMoms", category: "Healthcare & Maternity", summary: "Produced empathetic, medically sound social creative and educational carousels reaching thousands of parents.", route: "/work/#cloudnine" },
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Created dynamic reels and vehicle showcase content establishing strong brand presence in the commercial automotive space.", route: "/work/#cavalo" },
    ],
    faqs: [
      { question: "Which social platforms should my business be on?", answer: "Focus where your target buyers naturally spend attention. For B2B and technology companies, LinkedIn and YouTube are essential. For consumer, automotive, and lifestyle brands, Instagram, Meta, and YouTube deliver the highest brand discovery and engagement." },
      { question: "Do you produce original videos or use stock footage?", answer: "We prioritize original creative assets. We shoot, edit, and animate bespoke video content, infographics, and carousels tailored to your brand identity." },
      { question: "How does social media connect to lead generation?", answer: "We embed clear conversion pathways into content: link-in-bio landing pages, downloadable guides, webinar registrations, and direct message inquiry workflows that transition engaged users into your sales pipeline." },
    ],
  },
  "content-marketing": {
    slug: "content-marketing",
    route: "/digital-marketing/content-marketing",
    parentRoute: "/digital-marketing",
    parentLabel: "Digital Marketing",
    title: "Content Marketing Services | Pillar Pages, Case Studies & Strategy | SARS Global",
    eyebrow: "Content & Funnel Strategy",
    metaDescription: "Accelerate sales cycles with SARS Global's content marketing services: authoritative editorial, technical whitepapers, case studies, and conversion copywriting.",
    heroHeadline: "Strategic Content Marketing That Educates and Converts",
    heroSubheadline: "We produce research-backed, high-utility editorial content that answers buyer objections, builds domain authority, and fuels your entire marketing and sales pipeline.",
    badges: ["Editorial Content Strategy", "Pillar Articles & Topic Clusters", "B2B Case Study Production", "Technical Whitepapers & Ebooks", "Lead Magnet Development", "SEO Copywriting"],
    challenge: {
      title: "The Content Marketing Dilemma",
      description: "The internet is flooded with generic, surface-level AI content that prospects ignore. Buyers evaluate partners based on demonstrated subject matter depth, specific real-world examples, and actionable commercial insight.",
      points: [
        "Generic blog posts that generate empty traffic without educating prospective buyers",
        "Lack of mid-funnel content to address specific procurement and technical objections",
        "Case studies written like dry corporate press releases instead of compelling stories",
        "Inability to repurpose high-value written assets into multi-channel marketing collateral",
      ],
    },
    solutions: [
      {
        title: "Content Strategy & Buyer Journey Mapping",
        desc: "Researching what your prospects search, read, and discuss during their buying decisions to create targeted content roadmaps.",
        deliverables: ["Customer interview synthesis", "Content gap & competitive audits", "Funnel stage content mapping", "Editorial calendar management"],
      },
      {
        title: "High-Authority Pillar Content",
        desc: "In-depth, 2,500+ word guides that establish industry leadership and rank comprehensively for high-intent search queries.",
        deliverables: ["Primary topic pillar guides", "Supporting spoke articles", "Infographics & visual frameworks", "Schema.org Article & FAQ markup"],
      },
      {
        title: "B2B Case Studies & Customer Proof",
        desc: "Compelling customer success stories that highlight real business challenges, implementation methodology, and verified results.",
        deliverables: ["Stakeholder interview conduct", "Problem-solution-outcome framing", "Visual data callouts & quotes", "Sales enablement PDF versions"],
      },
      {
        title: "Gated Assets & Lead Magnets",
        desc: "High-value downloadable resources that motivate prospects to exchange contact information for actionable business intelligence.",
        deliverables: ["Industry benchmark reports", "Checklists and calculation templates", "Gated landing page copy", "Automated email delivery nurture sequences"],
      },
    ],
    process: [
      { step: "01", title: "Subject Matter Expert (SME) Extraction", desc: "We interview your internal leadership and specialists to extract proprietary insights and genuine domain expertise." },
      { step: "02", title: "Search & Competitive Modeling", desc: "We structure the content to answer high-intent user questions and outrank existing top competitor resources." },
      { step: "03", title: "Drafting & Visual Polish", desc: "Our experienced writers draft comprehensive content while our designers create custom charts and diagram assets." },
      { step: "04", title: "Distribution & Repurposing", desc: "We slice the master asset into LinkedIn carousels, newsletter highlights, social posts, and sales team battlecards." },
    ],
    techStack: ["Google Docs", "Figma", "Grammarly Business", "Ahrefs", "Semrush", "WordPress", "HubSpot"],
    caseStudies: [
      { name: "Light Financial Education", category: "Education", summary: "Developed accessible, engaging financial literacy content and curriculum guides for parents and educators.", route: "/work/#light-financial-education" },
      { name: "BenchKart", category: "B2B Tech", summary: "Authored technical articles and guides demystifying enterprise software procurement for business decision-makers.", route: "/work/#benchkart" },
    ],
    faqs: [
      { question: "How do you ensure content accuracy in technical industries?", answer: "We combine professional technical copywriters with a structured SME interview workflow. We capture your team's specific insights and terminology, followed by a strict review process before publishing." },
      { question: "Can content marketing assist our direct sales team?", answer: "Yes. We specifically build sales enablement content—one-pagers, case studies, comparison frameworks, and ROI breakdowns—that sales reps can send to prospects to accelerate deal closing." },
      { question: "How do you measure content marketing ROI?", answer: "We track organic keyword rankings, engaged reading time, content-assisted conversions, lead magnet downloads, and pipeline attribution to measure real business impact." },
    ],
  },
};
