import { ServiceData } from "./types";

export const SOFTWARE_DEVELOPMENT_SERVICES: Record<string, ServiceData> = {
  "hub": {
    slug: "software-development",
    route: "/software-development",
    title: "Software & Web Development Services | Next.js, React & Custom Apps | SARS Global",
    eyebrow: "Full-Cycle Software Engineering",
    metaDescription: "Build scalable, high-performance digital products with SARS Global: modern Next.js and React web apps, custom software platforms, WordPress, Shopify, and secure API architectures.",
    heroHeadline: "Scalable Software Engineering Built for High Performance",
    heroSubheadline: "We design, build, and maintain production-ready web applications, enterprise software platforms, bespoke eCommerce engines, and robust APIs engineered for security and speed.",
    badges: ["Next.js & React Applications", "Custom Cloud Software", "Enterprise WordPress Architecture", "High-Converting Shopify Stores", "REST & GraphQL APIs", "Microservices & Cloud DevOps"],
    challenge: {
      title: "The Danger of Low-Code Hacks and Fragile Codebases",
      description: "Fast-growing companies often outgrow template builders and disjointed plugin stacks. Slow load times, brittle architecture, technical debt, and security vulnerabilities hold back user retention and block scalable product expansion.",
      points: [
        "Monolithic websites burdened with dozens of unmaintained third-party plugins",
        "Slow load speeds and poor Core Web Vitals damaging search rankings and conversion rates",
        "Inability to scale infrastructure as transaction and user volumes surge",
        "Security vulnerabilities, unencrypted data stores, and lack of automated test suites",
      ],
    },
    solutions: [
      {
        title: "Modern Web Application Development",
        desc: "High-performance frontend and full-stack web applications built with Next.js, React, TypeScript, and modern headless architectures.",
        deliverables: ["Server-Side Rendered (SSR) & static pages", "Lighthouse 95+ Core Web Vitals performance", "Responsive mobile-first layouts", "SEO-optimized semantic DOM structure"],
      },
      {
        title: "Custom Enterprise Software & SaaS",
        desc: "End-to-end bespoke software systems, internal management portals, and multi-tenant SaaS platforms tailored to your business rules.",
        deliverables: ["Multi-tenant database architectures", "Role-Based Access Control (RBAC)", "Billing & subscription lifecycle integration", "Comprehensive automated test suites"],
      },
      {
        title: "Enterprise WordPress & Headless CMS",
        desc: "Custom WordPress themes and headless decoupled backends built with zero bloated page builders, ensuring lightning-fast load times.",
        deliverables: ["Custom Gutenberg block systems", "Security hardening & malware defense", "Advanced Custom Fields (ACF) modeling", "Decoupled headless Next.js frontends"],
      },
      {
        title: "eCommerce Engineering (Shopify & Custom)",
        desc: "High-converting online storefronts, custom checkout extensions, and ERP/inventory integrations built for maximum purchase conversion.",
        deliverables: ["Bespoke Shopify Liquid & Hydrogen themes", "Custom Shopify apps & private APIs", "Payment gateway & ERP synchronization", "Mobile speed & conversion checkout tuning"],
      },
    ],
    subServices: [
      {
        title: "Web Development",
        route: "/software-development/web-development",
        desc: "Modern corporate websites and web apps engineered with modern frameworks, rapid load speeds, and pristine UI fidelity.",
        deliverables: ["Next.js/React Apps", "Fast Performance", "Responsive Design", "SEO Architecture"],
      },
      {
        title: "Custom Software",
        route: "/software-development/custom-software",
        desc: "Bespoke internal tools, customer portals, and proprietary SaaS platforms built to solve your unique operational workflows.",
        deliverables: ["Bespoke Platforms", "Scalable Databases", "User Portals", "Enterprise Security"],
      },
      {
        title: "WordPress Development",
        route: "/software-development/wordpress-development",
        desc: "Custom WordPress theme and block development without slow page builders, optimized for speed, security, and editorial ease.",
        deliverables: ["Clean PHP/Gutenberg", "ACF Pro Modeling", "Security Hardened", "Blazing Fast Speeds"],
      },
      {
        title: "Shopify Development",
        route: "/software-development/shopify-development",
        desc: "Custom Shopify stores, Hydrogen headless setups, and private apps engineered to increase average order value and checkout conversions.",
        deliverables: ["Custom Liquid Themes", "Checkout Extensions", "App Integrations", "Speed Optimization"],
      },
      {
        title: "React Development",
        route: "/software-development/react-development",
        desc: "Interactive, reactive user interfaces and single-page applications built with clean component architectures and TypeScript.",
        deliverables: ["Component Libraries", "State Management", "TypeScript Safety", "Design System Sync"],
      },
      {
        title: "API Development",
        route: "/software-development/api-development",
        desc: "Secure, well-documented REST and GraphQL APIs connecting your mobile apps, web frontends, and external third-party services.",
        deliverables: ["REST & GraphQL", "Authentication & JWT", "Swagger/Postman Docs", "Rate Limiting & Caching"],
      },
    ],
    process: [
      { step: "01", title: "Product Discovery & Architecture", desc: "We translate your functional requirements into data models, system flowcharts, and technical architecture specifications." },
      { step: "02", title: "UI/UX Prototyping & Design Systems", desc: "Our product designers create interactive Figma prototypes and component style guides before code is written." },
      { step: "03", title: "Agile Sprint Development", desc: "We build features in 2-week sprints with automated CI/CD pipelines, code reviews, and weekly staging previews." },
      { step: "04", title: "QA Testing, Security & Cloud Launch", desc: "We perform automated test runs, penetration audits, and load testing before deploying on managed cloud infrastructure." },
    ],
    techStack: ["Next.js", "React", "TypeScript", "Node.js", "Python / Django", "PostgreSQL", "Tailwind CSS", "Shopify", "WordPress", "AWS / Vercel"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Automotive", summary: "Engineered responsive web platform and vehicle showcase portal with sub-second page loads and mobile-first UX.", route: "/work/#cavalo" },
      { name: "BenchKart", category: "Enterprise Marketplace", summary: "Architected multi-sided marketplace platform matching corporate buyers with verified technology providers.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Agritech Platform", summary: "Built mission-critical warehouse management data ingestion portals supporting agricultural supply chains.", route: "/work/#staragri" },
    ],
    faqs: [
      { question: "How do you ensure our software is secure and maintainable?", answer: "We enforce strict engineering standards: static TypeScript typing, modular folder architectures, OWASP security compliance, encrypted environment variables, automated unit/integration tests, and continuous integration (CI/CD) deployments." },
      { question: "Who owns the code and intellectual property?", answer: "You do. You retain 100% ownership of all source code, database designs, design assets, and production infrastructure upon project handover. We push code directly to your GitHub or GitLab repositories." },
      { question: "Do you provide post-launch maintenance and technical support?", answer: "Yes. We offer continuous SLA-backed maintenance packages covering server uptime, security patches, framework updates, feature additions, and ongoing performance tuning." },
    ],
  },
  "web-development": {
    slug: "web-development",
    route: "/software-development/web-development",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "Web Development Services | Next.js, Modern Jamstack & SSR | SARS Global",
    eyebrow: "Modern Web Engineering",
    metaDescription: "Build lightning-fast, conversion-focused websites with SARS Global. Expert Next.js, TypeScript, and responsive modern web development.",
    heroHeadline: "Next-Generation Web Development Built for Speed and Scale",
    heroSubheadline: "We build modern, accessible, and blindingly fast websites that deliver seamless user experiences, flawless Core Web Vitals, and strong commercial conversion rates.",
    badges: ["Next.js & React 19", "TypeScript Type Safety", "Core Web Vitals 95+", "Accessible WCAG AA UI", "Responsive Mobile-First", "Tailwind CSS Architecture"],
    challenge: {
      title: "Why Traditional Websites Suffer High Bounce Rates",
      description: "A 1-second delay in page load time can reduce conversions by up to 20%. Cluttered templates and outdated JavaScript frameworks weigh down modern browsers, turning away prospective buyers before the hero section even loads.",
      points: [
        "Heavy client-side bundles causing noticeable layout shifts and sluggish mobile performance",
        "Poor SEO performance resulting from non-semantic HTML and client-only rendering",
        "Broken mobile layouts across various device viewport widths and orientations",
        "Rigid CMS setups that require a developer just to update a line of marketing copy",
      ],
    },
    solutions: [
      {
        title: "Hybrid SSR & Static Generation",
        desc: "Leveraging Next.js App Router for hybrid rendering: static generation for speed and dynamic server rendering where real-time personalization is needed.",
        deliverables: ["Sub-second First Contentful Paint (FCP)", "Zero layout shifts (CLS < 0.05)", "Edge caching & CDN distribution", "Automated image compression & WebP/AVIF"],
      },
      {
        title: "Design System & Component Architecture",
        desc: "Bespoke reusable component libraries built in React and Tailwind CSS that ensure visual harmony and rapid feature development.",
        deliverables: ["Tailwind CSS utility architecture", "Accessible interactive elements (Radix UI/Headless)", "Micro-interactions and fluid transitions", "Cross-browser regression testing"],
      },
      {
        title: "Search Engine Optimized DOM Structure",
        desc: "Clean semantic HTML5 markup, structured metadata, open-graph tags, and dynamic Schema.org JSON-LD built directly into every page.",
        deliverables: ["Valid semantic HTML hierarchy", "Automated dynamic XML sitemaps", "Social sharing OpenGraph cards", "JSON-LD structured data integration"],
      },
      {
        title: "Headless CMS Integration",
        desc: "Empower your marketing team to create and publish landing pages without writing code using modern headless CMS tools.",
        deliverables: ["Sanity, Strapi or Contentful setup", "Visual live content previewing", "Custom editorial schemas", "Role-based editorial permissions"],
      },
    ],
    process: [
      { step: "01", title: "Information Architecture & UX Wireframes", desc: "We structure page user flows, conversion pathways, and technical specifications." },
      { step: "02", title: "Component Development & State Modeling", desc: "We write clean, modular TypeScript components with strict props validation and responsive layouts." },
      { step: "03", title: "CMS & Third-Party Integrations", desc: "We hook up form endpoints, CRM webhooks, analytics pixels, and content management APIs." },
      { step: "04", title: "Performance Audits & Global Edge Launch", desc: "We run deep Lighthouse audits, fix all bottlenecks, and deploy to edge networks with SSL and CDN caching." },
    ],
    techStack: ["Next.js 15+", "React 19", "TypeScript", "Tailwind CSS", "Node.js", "Sanity / Strapi", "Vercel / Cloudflare"],
    caseStudies: [
      { name: "Cavalo", category: "Automotive", summary: "Delivered a high-impact digital experience showcasing vehicle specifications with sub-second page loads.", route: "/work/#cavalo" },
      { name: "Light Financial Education", category: "FinTech Education", summary: "Engineered an intuitive, friendly educational portal with interactive calculators and responsive learning modules.", route: "/work/#light-financial-education" },
    ],
    faqs: [
      { question: "Why do you recommend Next.js over traditional WordPress?", answer: "Next.js delivers unmatched loading speeds, superior security (no database vulnerabilities exposed to the public web), and exceptional developer flexibility, giving your users an app-like browsing experience." },
      { question: "Will the website be easy for our non-technical team to update?", answer: "Yes. By pairing Next.js with a headless CMS like Sanity, Contentful, or Strapi, your marketing team can publish new blog posts, change banner text, and launch landing pages through a clean, intuitive editor." },
      { question: "Do you build custom designs or use pre-made templates?", answer: "We build 100% bespoke designs tailored to your brand identity, target demographic, and conversion goals. We do not use generic off-the-shelf templates." },
    ],
  },
  "custom-software": {
    slug: "custom-software",
    route: "/software-development/custom-software",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "Custom Software Development Services | SaaS & Cloud Systems | SARS Global",
    eyebrow: "Bespoke Software Engineering",
    metaDescription: "Solve unique business challenges with SARS Global's custom software development services: multi-tenant SaaS, client portals, internal ERPs, and cloud databases.",
    heroHeadline: "Bespoke Software Solutions Engineered for Your Business Logic",
    heroSubheadline: "When off-the-shelf software forces you into painful workarounds, we build tailored software platforms, internal operations tools, and SaaS products that give you an unfair competitive edge.",
    badges: ["Multi-Tenant SaaS Architecture", "Bespoke Internal Portals & ERPs", "Relational & NoSQL Databases", "Role-Based Access Control (RBAC)", "Enterprise Cloud Infrastructure", "Automated CI/CD Pipelines"],
    challenge: {
      title: "The Problem with Rigid Off-The-Shelf SaaS",
      description: "Generic commercial software is designed for everyone, which means it fits no one's exact operational requirements. Businesses end up paying expensive per-seat subscription fees while wrestling with manual workarounds and missing features.",
      points: [
        "Mounting recurring monthly SaaS licensing costs as your team headcount expands",
        "Disjointed internal workflows forced into rigid generic software frameworks",
        "Lack of proprietary data ownership and risk of vendor lock-in",
        "Inability to rapidly deploy new internal features tailored to your market advantage",
      ],
    },
    solutions: [
      {
        title: "Bespoke Cloud Portals & Back-Office Tools",
        desc: "Custom management consoles, customer dashboards, and partner portals that unify your internal operations into one intuitive interface.",
        deliverables: ["Role-Based Access Control (RBAC)", "Interactive analytics & data visualization", "Audit logging & compliance trails", "Automated operational alerts"],
      },
      {
        title: "SaaS Product Development (MVP to Scale)",
        desc: "Turn your software product vision into a scalable, secure, and revenue-generating multi-tenant commercial application.",
        deliverables: ["Multi-tenant database tenancy isolation", "Stripe billing & subscription metering", "Team workspaces & user seat management", "Self-service onboarding & product tours"],
      },
      {
        title: "Data Architecture & Migration",
        desc: "Robust relational (PostgreSQL) and document database architectures engineered for high-concurrency queries and transactional integrity.",
        deliverables: ["Normalized relational schemas & indexing", "Zero-downtime data migration scripts", "Automated point-in-time database backups", "Read replica & caching layers (Redis)"],
      },
      {
        title: "Cloud DevOps & Continuous Integration",
        desc: "Automated deployment pipelines and containerized microservices hosted on AWS, GCP, or Azure with auto-scaling capabilities.",
        deliverables: ["Docker containerization", "GitHub Actions CI/CD pipelines", "Kubernetes / AWS ECS orchestration", "Server monitoring and APM tracking"],
      },
    ],
    process: [
      { step: "01", title: "Domain Discovery & Requirements Spec", desc: "We interview stakeholders to document all business rules, user personas, workflows, and security requirements." },
      { step: "02", title: "Architecture & Data Schema Design", desc: "We construct entity-relationship diagrams, API specifications, and cloud infrastructure topology." },
      { step: "03", title: "Sprint-Based Engineering", desc: "Our senior developers build functional modules in 2-week increments with automated testing and continuous code reviews." },
      { step: "04", title: "Penetration Testing, UAT & Launch", desc: "We conduct user acceptance testing, security vulnerability scans, and performance load tests before production deployment." },
    ],
    techStack: ["Node.js / Express / NestJS", "Python / FastAPI / Django", "TypeScript", "PostgreSQL", "Redis", "Docker", "AWS / GCP", "Next.js"],
    caseStudies: [
      { name: "BenchKart", category: "B2B Tech Platform", summary: "Built an end-to-end custom procurement engine with algorithmic vendor matching and milestone billing.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Agricultural Logistics", summary: "Developed real-time agricultural collateral management and warehouse inspection portals.", route: "/work/#staragri" },
    ],
    faqs: [
      { question: "How long does custom software development take?", answer: "A focused Minimum Viable Product (MVP) typically takes 8 to 14 weeks from kickoff to launch. Larger enterprise platforms with multiple integrations and complex role permissions generally span 4 to 8 months in iterative phases." },
      { question: "Can we integrate with our existing accounting and CRM software?", answer: "Yes. Custom software is designed specifically to interface with your current tools via REST, GraphQL, or webhook APIs, ensuring zero disruption to your existing business workflows." },
      { question: "How do you handle software scalability as our user base grows?", answer: "We architect cloud-native systems with stateless containerized application layers, database read replicas, and Redis caching. This allows your infrastructure to automatically scale horizontally to handle thousands of concurrent users without degradation." },
    ],
  },
  "wordpress-development": {
    slug: "wordpress-development",
    route: "/software-development/wordpress-development",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "Enterprise WordPress Development Services | Custom Gutenberg Themes | SARS Global",
    eyebrow: "CMS Engineering & WordPress Architecture",
    metaDescription: "High-performance custom WordPress development with zero bloat. SARS Global builds bespoke Gutenberg block themes, WooCommerce stores, and secure enterprise setups.",
    heroHeadline: "Enterprise WordPress Development Built for Speed and Security",
    heroSubheadline: "Say goodbye to slow, bloated page builders. We build custom, lightweight Gutenberg block themes and enterprise WordPress systems engineered for sub-second speeds and editorial ease.",
    badges: ["Zero Bloated Page Builders", "Custom Gutenberg Block Libraries", "Advanced Custom Fields (ACF Pro)", "Enterprise Security Hardening", "WooCommerce Customization", "Sub-Second Page Loads"],
    challenge: {
      title: "The Reality of Bloated WordPress Websites",
      description: "Most agencies build WordPress sites by stacking heavy visual page builders (Elementor, Divi) and 40+ plugins together. The result is a slow, fragile website that breaks on every core update and exposes security vulnerabilities.",
      points: [
        "Sluggish page load speeds (often 5+ seconds) driving mobile visitors away",
        "Plugin conflicts causing white-screen crashes during routine WordPress updates",
        "Vulnerable, outdated third-party code putting sensitive customer data at risk",
        "Confusing admin backend experiences that make simple copy changes frustrating",
      ],
    },
    solutions: [
      {
        title: "Bespoke Gutenberg Block Themes",
        desc: "Custom lightweight WordPress themes built natively using the Gutenberg block editor with modular, reusable content blocks.",
        deliverables: ["Zero commercial page builder dependencies", "Custom native React Gutenberg blocks", "Lightweight semantic HTML and CSS", "Clean, intuitive editorial editing UI"],
      },
      {
        title: "Structured Content & ACF Pro Modeling",
        desc: "Tailored data architectures using Advanced Custom Fields (ACF Pro) ensuring marketing editors cannot accidentally break page styling.",
        deliverables: ["Custom post types (Case Studies, Team, Services)", "Structured flexible layout blocks", "Automated image sizing and lazy loading", "Strict field validation rules"],
      },
      {
        title: "Enterprise Security & Malware Defense",
        desc: "Complete hardening of your WordPress installation: two-factor authentication, database prefix salting, and automated web application firewalls.",
        deliverables: ["Cloudflare Enterprise WAF integration", "XML-RPC and brute-force login shielding", "Automated daily offsite cloud backups", "Zero-vulnerability plugin governance"],
      },
      {
        title: "WooCommerce Performance Customization",
        desc: "Custom WooCommerce storefronts and checkout flows stripped of standard eCommerce bloat for rapid checkout completion.",
        deliverables: ["Streamlined one-page checkout flows", "Custom payment gateway & shipping integrations", "Inventory & ERP synchronization", "Cart abandonment recovery workflows"],
      },
    ],
    process: [
      { step: "01", title: "Information Architecture & Custom Fields Plan", desc: "We map your content requirements into custom post types and field structures." },
      { step: "02", title: "Custom Theme & Block Development", desc: "We hand-code your custom WordPress theme and Gutenberg blocks using modern PHP and React." },
      { step: "03", title: "Content Migration & Editorial Setup", desc: "We cleanly migrate existing articles, media, and SEO metadata into the new structured layout." },
      { step: "04", title: "Speed Optimization & Go-Live", desc: "We implement object caching, configure server headers, run security audits, and deploy with zero downtime." },
    ],
    techStack: ["WordPress Core (Modern PHP 8+)", "Gutenberg / React", "ACF Pro", "WooCommerce", "MySQL", "Redis Object Cache", "Cloudflare"],
    caseStudies: [
      { name: "Cloudnine KnowMoms", category: "Healthcare Media", summary: "Built a high-traffic WordPress content platform handling thousands of daily readers with rapid load speeds.", route: "/work/#cloudnine" },
      { name: "Avance Consulting", category: "Corporate Services", summary: "Developed custom corporate WordPress presence with dynamic career listings and global office directories.", route: "/work/#avance-consulting" },
    ],
    faqs: [
      { question: "Do you use Elementor or Divi?", answer: "No. We specifically avoid heavy third-party page builders because they generate massive DOM sizes, inject hundreds of redundant CSS/JS files, and slow down your website. We build with native WordPress Gutenberg blocks for clean code and maximum speed." },
      { question: "How fast will our custom WordPress site load?", answer: "Our custom WordPress builds consistently achieve sub-second load times and 90+ mobile Performance scores on Google PageSpeed Insights, even with rich photography and interactive elements." },
      { question: "Can you migrate our existing WordPress content without losing SEO rankings?", answer: "Yes. We execute seamless migrations preserving your exact URL structures, heading hierarchies, meta tags, and internal link graph so your search engine rankings are protected." },
    ],
  },
  "shopify-development": {
    slug: "shopify-development",
    route: "/software-development/shopify-development",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "Shopify Development Services | Custom Liquid & Headless Hydrogen | SARS Global",
    eyebrow: "eCommerce Engineering & Store Architecture",
    metaDescription: "Accelerate eCommerce sales with SARS Global's Shopify development services: custom Liquid themes, Hydrogen headless storefronts, and checkout optimization.",
    heroHeadline: "Custom Shopify Engineering That Converts Visitors into Customers",
    heroSubheadline: "We build bespoke Shopify and Shopify Plus storefronts engineered for fast mobile loading, high conversion rates, and seamless backend operational integration.",
    badges: ["Custom Shopify Liquid Themes", "Shopify Plus Enterprise Architecture", "Shopify Hydrogen (Headless)", "Checkout Extensibility & CRO", "Private Shopify App Development", "ERP & Inventory Sync"],
    challenge: {
      title: "Why Generic Shopify Themes Hurt Sales",
      description: "Pre-made marketplace Shopify themes are packed with unused code and bloated scripts designed to appeal to every type of merchant. As you install apps to add basic features, page speed plummets and mobile abandonment rates spike.",
      points: [
        "Slow mobile load speeds causing shoppers to bounce before product pages render",
        "Clashing third-party Shopify apps creating layout bugs and slowing down checkout",
        "Generic theme layouts that fail to convey brand premiumness and product value",
        "Lack of custom upsell, bundle, and subscription mechanics in the native cart",
      ],
    },
    solutions: [
      {
        title: "Bespoke Shopify Theme Engineering",
        desc: "Hand-coded Shopify themes built using lightweight Liquid and modern JavaScript tailored precisely to your brand visual identity.",
        deliverables: ["Custom Section & Block architecture in Theme Editor", "Mobile-first responsive UX", "Native swatch, bundle, and size-guide modules", "Zero third-party script bloat"],
      },
      {
        title: "Shopify Checkout Extensibility & CRO",
        desc: "Customize the Shopify Plus checkout with post-purchase upsells, custom shipping rules, and branded trust badges.",
        deliverables: ["One-click post-purchase upsell offers", "Dynamic cart drawer with threshold progress bars", "Custom checkout fields & validation", "Payment gateway optimization (Apple Pay, Shop Pay)"],
      },
      {
        title: "Headless Shopify (Hydrogen & Next.js)",
        desc: "For fast-scaling brands needing ultimate performance: decoupled storefronts powered by Shopify Storefront API and Next.js.",
        deliverables: ["Next.js / Remix frontend storefront", "Sub-second global edge page loads", "Custom interactive 3D product visualizers", "International localized currencies and languages"],
      },
      {
        title: "Private Apps & Backend ERP Integrations",
        desc: "Automate your fulfillment, warehouse, and accounting operations by connecting Shopify directly to your ERP and inventory tools.",
        deliverables: ["Custom private Shopify apps", "Two-way inventory and order sync", "Custom fulfillment and returns webhooks", "Klaviyo and loyalty program synchronization"],
      },
    ],
    process: [
      { step: "01", title: "eCommerce UX & Conversion Strategy", desc: "We design product page layouts, cart funnels, and navigation architectures geared toward maximizing AOV and conversion rate." },
      { step: "02", title: "Clean Theme Development", desc: "We hand-code custom Liquid sections and interactive components natively in the Shopify 2.0 theme framework." },
      { step: "03", title: "App Consolidation & Speed Tuning", desc: "We replace slow, redundant third-party apps with native theme code, drastically accelerating page load speed." },
      { step: "04", title: "Payment & Order QA Testing", desc: "We run end-to-end test orders across multiple currencies, gateways, discount codes, and fulfillment endpoints before go-live." },
    ],
    techStack: ["Shopify Liquid", "Shopify Storefront API", "Shopify Hydrogen", "Next.js", "Tailwind CSS", "Klaviyo API", "Stripe"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Storefront", summary: "Built customized quotation and product inquiry catalog workflows tailored for commercial vehicle buyers.", route: "/work/#cavalo" },
      { name: "BenchKart", category: "B2B Tech", summary: "Configured multi-tier pricing and milestone deposit collection workflows for enterprise services.", route: "/work/#benchkart" },
    ],
    faqs: [
      { question: "Can our marketing team edit product and collection pages easily?", answer: "Yes. We build entirely within the Shopify Online Store 2.0 architecture, creating flexible sections and blocks that your team can drag, drop, reorder, and update directly in the visual Theme Editor." },
      { question: "How do you improve Shopify page speed scores?", answer: "We eliminate redundant third-party app scripts, hard-code essential features natively into the theme, lazy-load images, and optimize font loading, consistently achieving mobile scores in the 85-95 range." },
      { question: "Do you support Shopify Plus migrations from WooCommerce or Magento?", answer: "Yes. We regularly handle complete migrations, safely transferring customer accounts, order history, products, collections, and 301 URL redirects without downtime or loss of SEO ranking." },
    ],
  },
  "react-development": {
    slug: "react-development",
    route: "/software-development/react-development",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "React Development Services | TypeScript & Single Page Applications | SARS Global",
    eyebrow: "Modern Frontend Engineering",
    metaDescription: "Build dynamic, scalable user interfaces with SARS Global's React development services: TypeScript architectures, state management, and modern component systems.",
    heroHeadline: "Modern React & TypeScript Engineering Built for Performance",
    heroSubheadline: "We build reactive, accessible, and type-safe user interfaces and web applications using modern React, clean component design patterns, and robust state management.",
    badges: ["React 19 & Server Components", "Strict TypeScript Safety", "Tailwind CSS & Headless UI", "Zustand & TanStack Query", "Design System Implementation", "Comprehensive Component Testing"],
    challenge: {
      title: "The Pitfalls of Unstructured React Applications",
      description: "Without disciplined architectural conventions, React projects quickly devolve into 'spaghetti code': unnecessary re-renders, uncontrolled prop drilling, memory leaks, and fragile component state that slows down feature releases.",
      points: [
        "Unoptimized component trees triggering constant redundant re-renders and laggy UI",
        "Lack of strict TypeScript typing resulting in runtime errors and regression bugs",
        "Disorganized state management making feature extension slow and bug-prone",
        "Inaccessible components failing basic WCAG screen-reader and keyboard tests",
      ],
    },
    solutions: [
      {
        title: "Clean Modular Component Architectures",
        desc: "We write clean, single-responsibility React components adhering to atomic design principles and strict TypeScript interfaces.",
        deliverables: ["Design token synchronization", "Accessible UI primitives (Radix / Headless UI)", "Storybook component documentation", "Zero prop-drilling state patterns"],
      },
      {
        title: "Efficient Server State & Caching",
        desc: "Eliminate complex Redux boilerplate with lightweight modern state tools like TanStack Query and Zustand for optimal client performance.",
        deliverables: ["Automatic background data re-fetching", "Optimistic UI updates for instant feedback", "Infinite scrolling and pagination", "Smart client-side caching layers"],
      },
      {
        title: "Fluid Animations & Micro-Interactions",
        desc: "Delightful, natural user feedback using Motion (Framer Motion) and CSS hardware-accelerated animations that never lag on mobile devices.",
        deliverables: ["Smooth layout transitions", "Interactive gestures & drag interactions", "Reduced-motion accessibility compliance", "Skeleton loading states"],
      },
      {
        title: "Automated Testing & Code Quality",
        desc: "End-to-end type safety and automated testing using Vitest, React Testing Library, and Playwright to guarantee stability across updates.",
        deliverables: ["Unit tests for complex business logic", "Integration tests for user journeys", "Automated GitHub Actions linting & builds", "Zero console warning deployments"],
      },
    ],
    process: [
      { step: "01", title: "Figma to Component Mapping", desc: "We audit your design files, extract reusable tokens (colors, typography, spacing), and structure the component hierarchy." },
      { step: "02", title: "State & API Architecture", desc: "We design data contracts, define TypeScript types, and establish server-state caching patterns." },
      { step: "03", title: "Iterative Component Build", desc: "We develop components with strict accessibility standards, responsiveness, and micro-interactions." },
      { step: "04", title: "Integration, Testing & Deployment", desc: "We integrate with backend APIs, run automated test suites, and deploy to modern global edge networks." },
    ],
    techStack: ["React 19", "TypeScript", "Next.js", "Tailwind CSS", "TanStack Query", "Zustand", "Motion", "Playwright"],
    caseStudies: [
      { name: "Cavalo", category: "Commercial Vehicles", summary: "Built dynamic vehicle configurators and interactive modal specifications in responsive React.", route: "/work/#cavalo" },
      { name: "BenchKart", category: "B2B Marketplace", summary: "Engineered responsive client dashboards and real-time proposal review interfaces in React.", route: "/work/#benchkart" },
    ],
    faqs: [
      { question: "Why use TypeScript with React?", answer: "TypeScript catches errors during development before code ever reaches production. It provides autocomplete, self-documenting code, and guarantees that your components receive the correct data types, drastically reducing runtime bugs." },
      { question: "Can you help migrate our legacy React codebase to modern standards?", answer: "Yes. We frequently modernize legacy React apps: upgrading class components to functional hooks, migrating from Create React App or webpack to Vite/Next.js, and introducing TypeScript and clean state management." },
      { question: "Do you build custom design systems in React?", answer: "Yes. We build bespoke UI component libraries paired with Storybook documentation, giving your internal development team reusable, branded building blocks for rapid product development." },
    ],
  },
  "api-development": {
    slug: "api-development",
    route: "/software-development/api-development",
    parentRoute: "/software-development",
    parentLabel: "Software Development",
    title: "API Development & Integration Services | REST, GraphQL & Webhooks | SARS Global",
    eyebrow: "Backend Engineering & API Architecture",
    metaDescription: "Build secure, high-throughput APIs with SARS Global: REST, GraphQL, microservices, third-party integrations, and comprehensive OpenAPI documentation.",
    heroHeadline: "Scalable API Architecture Built for High Throughput and Security",
    heroSubheadline: "We design, build, and document secure REST and GraphQL APIs that connect your frontend applications, mobile apps, third-party partners, and internal microservices.",
    badges: ["High-Throughput REST APIs", "GraphQL Schema Design", "JWT & OAuth 2.0 Authentication", "OpenAPI (Swagger) Documentation", "Rate Limiting & DDoS Defense", "Microservices & Serverless"],
    challenge: {
      title: "The Danger of Fragile, Undocumented APIs",
      description: "When APIs are built without consistent standards, schemas, or security safeguards, they quickly become a major bottleneck. Developers struggle to integrate, response latencies climb under load, and unprotected endpoints invite data breaches.",
      points: [
        "Inconsistent response formats and status codes frustrating frontend and mobile developers",
        "Lack of interactive documentation (OpenAPI/Swagger) slowing down third-party integrations",
        "Vulnerability to SQL injection, broken object-level authorization (BOLA), and rate abuse",
        "Slow query response times caused by unindexed database joins and lack of caching",
      ],
    },
    solutions: [
      {
        title: "REST & GraphQL API Architecture",
        desc: "Clean, idiomatic API endpoints designed following RESTful principles or GraphQL schemas tailored for high-concurrency client requests.",
        deliverables: ["Predictable resource naming & HTTP codes", "GraphQL queries, mutations & subscriptions", "Input validation & data sanitization", "Pagination, filtering & sorting standards"],
      },
      {
        title: "Enterprise Authentication & Security",
        desc: "Hardened authentication architectures using OAuth 2.0, OpenID Connect, JSON Web Tokens (JWT), and granular API key management.",
        deliverables: ["Role-Based Access Control (RBAC)", "API rate limiting & throttling (Redis)", "CORS policy governance", "Encrypted payload transmission (TLS 1.3)"],
      },
      {
        title: "Interactive OpenAPI (Swagger) Documentation",
        desc: "Auto-generated, interactive developer documentation allowing internal and external developers to test endpoints directly in their browser.",
        deliverables: ["Interactive Swagger/Postman collections", "Accurate request/response schemas", "Mock server environments for testing", "SDK code snippets in multiple languages"],
      },
      {
        title: "Webhook Engines & Event Streams",
        desc: "Reliable event publishing infrastructure that pushes real-time notifications to external systems with automatic retry mechanisms.",
        deliverables: ["Idempotent webhook delivery pipelines", "Cryptographic signature verification (HMAC)", "Dead-letter queues for failed deliveries", "Event streaming with Apache Kafka / RabbitMQ"],
      },
    ],
    process: [
      { step: "01", title: "API Contract & Schema First Design", desc: "We define OpenAPI/Swagger specifications collaboratively before writing backend logic." },
      { step: "02", title: "Endpoint Engineering & Data Validation", desc: "We implement controllers, services, and database repositories using strict schema validation." },
      { step: "03", title: "Caching, Indexing & Load Testing", desc: "We add Redis caching, optimize database queries, and simulate thousands of requests per second." },
      { step: "04", title: "Security Audits & Cloud Deployment", desc: "We conduct penetration testing, configure API gateway routing, and deploy with automated telemetry." },
    ],
    techStack: ["Node.js / Express / NestJS", "Python / FastAPI", "PostgreSQL", "Redis", "Docker", "AWS API Gateway", "GraphQL / Apollo", "Swagger / OpenAPI"],
    caseStudies: [
      { name: "BenchKart", category: "B2B Tech Platform", summary: "Engineered secure REST APIs powering buyer-seller requirement matching and escrow milestones.", route: "/work/#benchkart" },
      { name: "StarAgri", category: "Agritech Supply Chain", summary: "Built low-latency sync APIs connecting remote mobile warehouse scanners with central ERP databases.", route: "/work/#staragri" },
    ],
    faqs: [
      { question: "When should we choose GraphQL over REST?", answer: "REST is ideal for straightforward CRUD applications with predictable data access patterns. GraphQL is superior for complex applications with nested relational data where mobile clients need to fetch specific fields in a single network roundtrip to save bandwidth." },
      { question: "How do you protect APIs from unauthorized access and attacks?", answer: "We implement multiple security layers: OAuth2/JWT verification, strict input validation (Zod/Pydantic), Redis-based rate limiting per IP and API key, and automated Web Application Firewalls (WAF)." },
      { question: "Can you provide Postman collections for our frontend team?", answer: "Yes. Every API project includes a comprehensive, interactive Postman collection and Swagger UI documentation complete with sample request payloads, error states, and environment variable configs." },
    ],
  },
};
